// src/main/java/com/example/servlet/AddEmployeeServlet.java

package com.example.servlet;

import com.example.dao.EmployeeDao;
import com.example.model.Employee;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@WebServlet("/addEmployee")
public class AddEmployeeServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;
    private EmployeeDao employeeDao;

    public void init() {
        employeeDao = new EmployeeDao();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        
        // *Authentication Check Required Here (Step 1 from requirements):*
        if (request.getSession().getAttribute("userId") == null) {
            response.sendRedirect("login.jsp");
            return;
        }

        // 1. Get parameters (Perform necessary validations as per requirements)
        String name = request.getParameter("name");
        String gender = request.getParameter("gender");
        String designation = request.getParameter("designation");
        double salary = Double.parseDouble(request.getParameter("salary"));
        String city = request.getParameter("city");
        String emailId = request.getParameter("emailId");
        String mobileNo = request.getParameter("mobileNo");

        // 2. Create Employee object (ID is auto-generated by Hibernate)
        Employee employee = new Employee(name, gender, designation, salary, city, emailId, mobileNo);

        // 3. Save to database using DAO
        employeeDao.saveEmployee(employee);

        // 4. Display appropriate message to the end user
        request.setAttribute("message", "Employee " + name + " added successfully!");
        request.getRequestDispatcher("menu.jsp").forward(request, response);
    }
    
    protected void doGet(HttpServletRequest request, HttpServletResponse response) 
            throws ServletException, IOException {
        // Redirect to the form page
        request.getRequestDispatcher("add_employee_form.jsp").forward(request, response);
    }
}